### ISSUE TITLE
Bug(scope): Cannot find module '@jsverse/transloco-utils'

### ISSUE THREAD

**Issue by micobarac** [jsverse/transloco#873]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Which Transloco package(s) are the source of the bug?

Transloco

### Is this a regression?

No

### Current behavior

You messed up schematics & dependencies with v8. 

~/workspace/project (next)$ ng add @jsverse/transloco
✔ Determining Package Manager
  › Using package manager: yarn
✔ Searching for compatible package version
  › Found compatible package version: @jsverse/transloco@8.0.0.
✔ Loading package information from registry
✔ Confirming installation
✔ Installing package
Cannot find module '@jsverse/transloco-utils'
Require stack: ...

✘ [ERROR] TS2307: Cannot find module '@jsverse/utils' or its corresponding type declarations. [plugin angular-compiler]

    node_modules/@jsverse/transloco/lib/transloco.pipe.d.ts:2:24:
      2 │ import { OrArray } from '@jsverse/utils';
        ╵                         ~~~~~~~~~~~~~~~~

Cannot find module '@jsverse/transloco-utils' or its corresponding type declarations.

`ng add @jsverse/transloco` doesn't work on its own. You have to add these dependencies explicitely:

`yarn add @jsverse/utils @jsverse/transloco-utils`

But still, I get:

```
warning " > @jsverse/transloco@8.0.0" has incorrect peer dependency "@jsverse/utils@1.0.0-beta.5".
warning " > @jsverse/transloco@8.0.0" has unmet peer dependency "@jsverse/transloco-utils@^7.0.0".
```

### Expected behavior

Running:

`ng add @jsverse/transloco`

throws dependency errors, while it should only add `@jsverse/transloco@8.0.0` in package.json. 

### Please provide a link to a minimal reproduction of the bug, if you won't provide a link the issue won't be handled.

https://codesandbox.io/p/devbox/gallant-hermann-hx5rgc

### Transloco Config

```markdown
import { TranslocoGlobalConfig } from '@jsverse/transloco-utils';

const config: TranslocoGlobalConfig = {
  rootTranslationsPath: 'src/assets/i18n/',
  langs: ['en'],
  keysManager: {}
};

export default config;
```

### Please provide the environment you discovered this bug in

```markdown
Transloco: 8.0.0
Angular: 20.3.0
Node: 22.18
Package Manager: yarn
OS: MacOS
```

### Browser

```markdown

```

### Additional context

Transloco was perfect until the version 8.0.0, where the attempt to split it into separate modules broke the schematics & dependencies.

### I would like to make a pull request for this bug

Yes 🚀

**Comment by shaharkazaz** [comment]
@micobarac Can you please verify? a fix was pushed

**Comment by micobarac** [comment]
@shaharkazaz I checked and can confirm that the issue was fixed. Thanks for the fast response.
